In [ ]:
len?

In [ ]:
len?

In [ ]:
help(max)

In [ ]:
l=[1,2,3]

In [ ]:
l.insert?

In [ ]:
l?

In [ ]:
def square(a):
    """Return the square of a."""
    return a**2

In [ ]:
square?

In [ ]:
#accessing source
square??

In [ ]:
len??

In [ ]:
#Tab completion of object contentl

l.count(1)

In [ ]:
l.c#tab

private methods and special methods
are omitted from the list by default, but itâ€™s possible to list them by explicitly typing
the underscore:

In [ ]:
l._

In [ ]:
# tab with import 
p

In [ ]:
# Wildcard matching
*Warning?

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_excel("E:\CMP 404\BCA Student Data.xlsx")

In [3]:
df.shape

(19, 8)

In [4]:
df

,Enrollment No.,Student Name,Email,Programme,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,22000232,HET PRAGNESH KUMAR MEHTA,het.p.mehta@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,21
1,22000237,JAP JATIN SHAH,jap.j.shah@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,5
2,22000259,PARAKH AJAYKUMAR SHAH,parakh.a.shah@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,14
3,22000265,Qusai Shabbir Cutleriwala,qusai.s.cutlery@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,20
4,22000273,SAHAJ PRAMOD GAUTAM,sahaj.p.gautam@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,20
5,22000275,Sakshi Jigarkumar Shah,sakshi.j.shah@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,19
6,22000279,Smit Nimeshbhai Patel,smit.n.patel@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,12
7,22000280,SREEYA SWAIN,sreeya.swain@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,17
8,22000283,UNNATIBEN RATILAL ROHIT,unnatiben.r.rohit@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,7
9,22000286,VRAJ DIVYESHBHAI SONI,vraj.d.soni@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,19
10,22000287,VRUND DEVENDRA SHAH,vrund.d.shah@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,15
11,22000291,YASHVI ANIL KUMAR PATEL,yashvi.a.patel@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,13
12,22000518,FAKRUDDIN SHABBIR HUSEN,fakruddin.s.husen@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,14
13,22000541,PRATHAM NILESH JOSHI,pratham.n.joshi@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,27
14,22000550,JIYA FAKRUDDIN MUJAWAR,jiya.f.mujawar@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,13
15,22000557,Harshit Dineshbhai Parmar,harshit.d.parmar@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,7
16,22000582,MANTRA JOSHI,mantra.joshi@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,AAA
17,22000676,KHASIA VANSH SUNILBHAI,khasia.v.sunilbhai@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,28
18,22000707,DWEETI NIRAJKUMAR BHAVSAR,dweeti.n.bhavsar@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,16

In [9]:
df1=pd.read_excel("E:\CMP 404\BCA Student Data.xlsx",sheet_name=None)

In [15]:
df1['B']

,Enrollment No.,Student Name,Email,Programme,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,22000221,ASHISH BENJAMIN,ashish.benjamin@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,27.0
1,22000243,KRISHNA RAMCHAND KHANANI,krishna.r.khanani@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,18.0
2,22000252,MARIYAM MOHAMADANISH MEMON,mariyam.m.memon@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,20.0
3,22000256,NAJIBAH INTEKHAB SHAIKH,najibah.i.shaikh@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,7.5
4,22000267,Riya Pradipbhai Devre,riya.p.devre@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,15.0
5,22000269,ROHAN SUNIL AGARKAR,rohan.s.agarkar@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,28.0
6,22000270,Rushil Jayesh Patel,rushil.j.patel@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,27.0
7,22000271,SACHIN KAMLESH KUMAR CHHATANI,sachin.k.chhatani@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,22.0
8,22000272,SAGAR SINGH,sagar.singh@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,22.0
9,22000276,Sanchita Satishkumar Ramnani,sanchita.s.ramnani@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,15.0
10,22000285,VIKAS GURUPRASAD JAGURI,vikas.g.jaguri@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,13.0
11,22000290,YASH VARDHAN SINGH,yash.v.singh@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,28.0
12,22000515,HASTI DAVE,hasti.dave@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,13.0
13,22000516,MANAN AMIT MOMAYA,manan.a.momaya@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,26.5
14,22000517,Jaykishor Laxman Bhagat Kushwaha,jaykishor.l.kushwaha@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,16.0
15,22000519,MATIN NURUDDIN SHAIKH,matin.n.shaikh@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,28.0
16,22000544,KAPADWALA HAJI MOHAMMEDAFZAL,kapadwala.h.mohammedafzal@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,25.0
17,22000545,PATHAN AYMAAN,pathan.aymaan@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,23.0
18,22000553,VIVEK NANDLALBHAI RATHOD,vivek.n.rathod@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,13.0
19,22000558,DEVSHREE SUNIL JOSHI,devshree.s.joshi@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,28.0
20,22000568,FARDIN ARIF FODA,fardin.a.foda@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,28.0
21,22000514,KULDIPSINH GUNVANTSINH RATHOD,kuldipsinh.g.rathod@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,12.0
22,22000556,Purawala Ziyaanmahedi Mohammedhanif,purawala.z.mo.hanif@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,18.0
23,22000680,SURBHI ARORA,surbhi.arora@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,5.0

In [12]:
type(df1['A'])

pandas.core.frame.DataFrame

In [ ]:
df1[0].rename(columns={'Unnamed: 7':'Marks'},inplace= True)

In [ ]:
df1[1].rename(columns={'Unnamed: 7':'Marks'},inplace= True)

In [16]:
df1['D'].dropna(axis=1,inplace=True)

In [19]:
df1['D'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Enrollment No.  19 non-null     int64
 1   Student Name    19 non-null     object
 2   Email           19 non-null     object
 3   Programme       19 non-null     object
 4   Unnamed: 7      19 non-null     object
dtypes: int64(1), object(4)
memory usage: 892.0+ bytes

In [ ]:
df1[2]

In [ ]:
df1[3]

In [ ]:
df1

In [ ]:
df1

In [ ]:
type(df1)

In [ ]:
df1[0].Marks.dtype

In [ ]:
df1[0].Marks.astype(float)

In [ ]:
df1[0].Marks.replace("AAA",np.nan,inplace=True)

In [ ]:
df1[0].Marks

In [ ]:
df1[0].Marks<13

In [ ]:
df1[0]['Marks'].where((df1[0]['Marks']<13),"PASS")

In [ ]:
pd.DataFrame.where?

In [ ]:
df1[0]['Marks']

In [ ]:
df1[0]['Result']=df1[0]['Marks']

In [ ]:
df1[0]

In [ ]:
df1[0]['Result'].where((df1[0]['Result']>12),"Fail" ,inplace=True)

In [ ]:
df1[0]['Result'].mask((df1[0]['Result']>12),"Pass" ,inplace=True)

In [ ]:
df1[0]['Result']=np.where(df1[0]['Result']>12,"PASS","Fail")

In [ ]:
df1[1].Result.value_counts()

In [ ]:
df1[1]['Result']=df1[1]['Marks']

In [ ]:
df1[1]['Result']=np.where(df1[1]['Result']>12,"PASS","Fail")

In [ ]:
df1[1].replace("AAA",np.nan,inplace=True)

In [38]:
df1['A']

,Enrollment No.,Student Name,Email,Programme,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,22000210,AADIL IBRAR SHAIKH,aadil.i.shaikh@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,28.5
1,22000213,AAYUSHI AMIT DESAI,aayushi.a.desai@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,27.0
2,22000214,Abhiraj Chaudhuri,abhiraj.a.chaudhuri@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,29.0
3,22000215,ABHISHEKARUN KAVITA YADAV,abhishekarun.k.yadav@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,16.0
4,22000216,AJIN K JAMES,ajin.k.james@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,25.0
5,22000218,ARCHI DHAVAL VYAS,archi.d.vyas@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,11.0
6,22000219,ARPAN VALMIK PAWAR,arpan.v.pawar@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,13.0
7,22000220,ARYA DHAVAL VYAS,arya.d.vyas@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,15.0
8,22000225,DEVANSHI SANKETKUMAR GURUJI,devanshi.s.guruji@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,14.0
9,22000227,DRASHTI DILIPBHAI BHENSDADIA,drashti.d.bhensdadia@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,17.0
10,22000231,HARSH NARESH KHUSHALANI,harsh.n.khushalani@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,13.0
11,22000233,Hetvi Sanjay Pandya,hetvi.s.pandya@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,6.0
12,22000238,JEEVESH BHARDWAJ,jeevesh.bhardwaj@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,17.0
13,22000240,KASHVI AMITBHAI PATEL,kashvi.a.patel@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,22.0
14,22000244,KRISHNA SHARMA,krishna.sharma@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,8.0
15,22000246,LIZA PIYUSH GONDIA,liza.p.gondia@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,10.0
16,22000248,MAHEK JIGAR SHAH,mahek.j.shah@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,23.0
17,22000249,MAHIM HUSSAIN MIR,mahim.h.mir@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,17.0
18,22000253,MOHAMMED ARSHIL,mohammed.arshil@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,18.0
19,22000257,Nandani Kailash Agrawal,nandani.agrawal@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,29.0
20,22000266,RAJVEER HARESH JAGYASI,rajveer.h.jagyasi@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,7.0
21,22000268,RIYA KRUNALSINH THAKOR,riya.k.thakor@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,22.0
22,22000278,SHWETA RAJESH SOLANKI,shweta.r.solanki@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,24.0
23,22000559,DIYA KETAN THAKKAR,diya.k.thakkar@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,20.0
24,22000781,Tarvani Parita Chunilal,parita.c.tarwvani@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,27.0

he fillna() method, which returns a copy of the array with the null values
replaced.

In [14]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [16]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [17]:
data.fillna(method='ffill') #ffill bfill

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

For DataFrames, the options are similar, but we can also specify an axis along which
the fills take place:

In [18]:
df = pd.DataFrame([[1, np.nan, 2],
 [2, 3, 5],
 [np.nan, 4, 6]])

In [19]:
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [20]:
df.fillna(method='ffill', axis=1)

     0    1    2
0  1.0  1.0  2.0
1  2.0  3.0  5.0
2  NaN  4.0  6.0

In [39]:
A=df1['A']

In [40]:
A

,Enrollment No.,Student Name,Email,Programme,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,22000210,AADIL IBRAR SHAIKH,aadil.i.shaikh@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,28.5
1,22000213,AAYUSHI AMIT DESAI,aayushi.a.desai@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,27.0
2,22000214,Abhiraj Chaudhuri,abhiraj.a.chaudhuri@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,29.0
3,22000215,ABHISHEKARUN KAVITA YADAV,abhishekarun.k.yadav@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,16.0
4,22000216,AJIN K JAMES,ajin.k.james@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,25.0
5,22000218,ARCHI DHAVAL VYAS,archi.d.vyas@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,11.0
6,22000219,ARPAN VALMIK PAWAR,arpan.v.pawar@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,13.0
7,22000220,ARYA DHAVAL VYAS,arya.d.vyas@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,15.0
8,22000225,DEVANSHI SANKETKUMAR GURUJI,devanshi.s.guruji@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,14.0
9,22000227,DRASHTI DILIPBHAI BHENSDADIA,drashti.d.bhensdadia@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,17.0
10,22000231,HARSH NARESH KHUSHALANI,harsh.n.khushalani@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,13.0
11,22000233,Hetvi Sanjay Pandya,hetvi.s.pandya@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,6.0
12,22000238,JEEVESH BHARDWAJ,jeevesh.bhardwaj@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,17.0
13,22000240,KASHVI AMITBHAI PATEL,kashvi.a.patel@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,22.0
14,22000244,KRISHNA SHARMA,krishna.sharma@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,8.0
15,22000246,LIZA PIYUSH GONDIA,liza.p.gondia@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,10.0
16,22000248,MAHEK JIGAR SHAH,mahek.j.shah@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,23.0
17,22000249,MAHIM HUSSAIN MIR,mahim.h.mir@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,17.0
18,22000253,MOHAMMED ARSHIL,mohammed.arshil@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,18.0
19,22000257,Nandani Kailash Agrawal,nandani.agrawal@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,29.0
20,22000266,RAJVEER HARESH JAGYASI,rajveer.h.jagyasi@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,7.0
21,22000268,RIYA KRUNALSINH THAKOR,riya.k.thakor@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,22.0
22,22000278,SHWETA RAJESH SOLANKI,shweta.r.solanki@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,24.0
23,22000559,DIYA KETAN THAKKAR,diya.k.thakkar@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,20.0
24,22000781,Tarvani Parita Chunilal,parita.c.tarwvani@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,27.0

In [43]:
A.dropna(axis=1,inplace=True)

In [51]:
A.rename(columns={'Unnamed: 7':'Marks'},inplace=True)

In [52]:
A

,Enrollment No.,Student Name,Email,Programme,Marks
0,22000210,AADIL IBRAR SHAIKH,aadil.i.shaikh@nuv.ac.in,Bachelor of Computer Applications,28.5
1,22000213,AAYUSHI AMIT DESAI,aayushi.a.desai@nuv.ac.in,Bachelor of Computer Applications,27.0
2,22000214,Abhiraj Chaudhuri,abhiraj.a.chaudhuri@nuv.ac.in,Bachelor of Computer Applications,29.0
3,22000215,ABHISHEKARUN KAVITA YADAV,abhishekarun.k.yadav@nuv.ac.in,Bachelor of Computer Applications,16.0
4,22000216,AJIN K JAMES,ajin.k.james@nuv.ac.in,Bachelor of Computer Applications,25.0
5,22000218,ARCHI DHAVAL VYAS,archi.d.vyas@nuv.ac.in,Bachelor of Computer Applications,11.0
6,22000219,ARPAN VALMIK PAWAR,arpan.v.pawar@nuv.ac.in,Bachelor of Computer Applications,13.0
7,22000220,ARYA DHAVAL VYAS,arya.d.vyas@nuv.ac.in,Bachelor of Computer Applications,15.0
8,22000225,DEVANSHI SANKETKUMAR GURUJI,devanshi.s.guruji@nuv.ac.in,Bachelor of Computer Applications,14.0
9,22000227,DRASHTI DILIPBHAI BHENSDADIA,drashti.d.bhensdadia@nuv.ac.in,Bachelor of Computer Applications,17.0
10,22000231,HARSH NARESH KHUSHALANI,harsh.n.khushalani@nuv.ac.in,Bachelor of Computer Applications,13.0
11,22000233,Hetvi Sanjay Pandya,hetvi.s.pandya@nuv.ac.in,Bachelor of Computer Applications,6.0
12,22000238,JEEVESH BHARDWAJ,jeevesh.bhardwaj@nuv.ac.in,Bachelor of Computer Applications,17.0
13,22000240,KASHVI AMITBHAI PATEL,kashvi.a.patel@nuv.ac.in,Bachelor of Computer Applications,22.0
14,22000244,KRISHNA SHARMA,krishna.sharma@nuv.ac.in,Bachelor of Computer Applications,8.0
15,22000246,LIZA PIYUSH GONDIA,liza.p.gondia@nuv.ac.in,Bachelor of Computer Applications,10.0
16,22000248,MAHEK JIGAR SHAH,mahek.j.shah@nuv.ac.in,Bachelor of Computer Applications,23.0
17,22000249,MAHIM HUSSAIN MIR,mahim.h.mir@nuv.ac.in,Bachelor of Computer Applications,17.0
18,22000253,MOHAMMED ARSHIL,mohammed.arshil@nuv.ac.in,Bachelor of Computer Applications,18.0
19,22000257,Nandani Kailash Agrawal,nandani.agrawal@nuv.ac.in,Bachelor of Computer Applications,29.0
20,22000266,RAJVEER HARESH JAGYASI,rajveer.h.jagyasi@nuv.ac.in,Bachelor of Computer Applications,7.0
21,22000268,RIYA KRUNALSINH THAKOR,riya.k.thakor@nuv.ac.in,Bachelor of Computer Applications,22.0
22,22000278,SHWETA RAJESH SOLANKI,shweta.r.solanki@nuv.ac.in,Bachelor of Computer Applications,24.0
23,22000559,DIYA KETAN THAKKAR,diya.k.thakkar@nuv.ac.in,Bachelor of Computer Applications,20.0
24,22000781,Tarvani Parita Chunilal,parita.c.tarwvani@nuv.ac.in,Bachelor of Computer Applications,27.0

In [54]:
B=df1['B']

,Enrollment No.,Student Name,Email,Programme,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,22000221,ASHISH BENJAMIN,ashish.benjamin@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,27.0
1,22000243,KRISHNA RAMCHAND KHANANI,krishna.r.khanani@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,18.0
2,22000252,MARIYAM MOHAMADANISH MEMON,mariyam.m.memon@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,20.0
3,22000256,NAJIBAH INTEKHAB SHAIKH,najibah.i.shaikh@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,7.5
4,22000267,Riya Pradipbhai Devre,riya.p.devre@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,15.0
5,22000269,ROHAN SUNIL AGARKAR,rohan.s.agarkar@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,29.0
6,22000270,Rushil Jayesh Patel,rushil.j.patel@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,28.0
7,22000271,SACHIN KAMLESH KUMAR CHHATANI,sachin.k.chhatani@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,22.0
8,22000272,SAGAR SINGH,sagar.singh@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,22.0
9,22000276,Sanchita Satishkumar Ramnani,sanchita.s.ramnani@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,15.0
10,22000285,VIKAS GURUPRASAD JAGURI,vikas.g.jaguri@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,13.0
11,22000290,YASH VARDHAN SINGH,yash.v.singh@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,29.0
12,22000515,HASTI DAVE,hasti.dave@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,13.0
13,22000516,MANAN AMIT MOMAYA,manan.a.momaya@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,26.5
14,22000517,Jaykishor Laxman Bhagat Kushwaha,jaykishor.l.kushwaha@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,16.0
15,22000519,MATIN NURUDDIN SHAIKH,matin.n.shaikh@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,28.0
16,22000544,KAPADWALA HAJI MOHAMMEDAFZAL,kapadwala.h.mohammedafzal@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,25.0
17,22000545,PATHAN AYMAAN,pathan.aymaan@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,23.0
18,22000553,VIVEK NANDLALBHAI RATHOD,vivek.n.rathod@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,13.0
19,22000558,DEVSHREE SUNIL JOSHI,devshree.s.joshi@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,28.0
20,22000568,FARDIN ARIF FODA,fardin.a.foda@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,28.0
21,22000514,KULDIPSINH GUNVANTSINH RATHOD,kuldipsinh.g.rathod@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,12.0
22,22000556,Purawala Ziyaanmahedi Mohammedhanif,purawala.z.mo.hanif@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,18.0
23,22000680,SURBHI ARORA,surbhi.arora@nuv.ac.in,Bachelor of Computer Applications,NaN,NaN,NaN,5.0

In [ ]:
A.dropna(axis=1,inplace=True)

In [2]:
import numpy as np 
X,y=np.arange(10).reshape(2,5), range(5)

In [3]:
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
y

range(0, 5)

In [5]:
from sklearn.model_selection import  train_test_split

In [6]:
X_train , X_test,y_train,y_test=train_test_split(X,y)

ValueError: Found input variables with inconsistent numbers of samples: [2, 5]